### PR TITLE
new license key that supports Intel MPI

### PR DESCRIPTION
**Pull request by jeffhammond**
[ci skip] because this should only work for nemequ/icc-travis not
jeffhammond/icc-travis...

I will email you to confirm that this is an acceptable thing to do.

### CODE REVIEW

**Comment by nemequ** [comment]
Yep, that was the problem, thanks!  I've merged everything into master now, with all builds enabled.

FWIW, if you (or Intel) would like, I'd be happy to transfer ownership of this repo.  I'm guessing not, but consider the offer open.

**Comment by jeffhammond** [comment]
No need to transfer.  I have a fork and that is sufficient.  If you ever want to delete your repo, maybe you can set the redirect to mine so no one ends up lost.

**Comment by nemequ** [comment]
I don't see a reason I'd ever delete it.  However, now that I think about it, do you mind if I add you as an admin for the project, just in case anything happens to me?

**Comment by jeffhammond** [comment]
Sure.  And after I have permissions, I'll likely delete my repo so that there is no confusion which one is the right one to use.  I can always keep any of the hacks in a branch.

**Pull request closed without merging**
