### PR TITLE
test more components

### PR DESCRIPTION
**Pull request by jeffhammond**
I wrote tests for most of the tools.  Perhaps you want to add them.
In order for the tests to pass by default, I changed the default components to include Fortran, MPI, MKL, etc.
Feel free to reject the PR and cherry-pick what you want.  Some of my changes may be unnecessary for you.

### CODE REVIEW

**Comment by nemequ** [comment]
Thanks!  I've been wanting to test other components, so I'm quite happy about having some test cases to work with.  I'll merge most of this; I'll have to skip the commit where you change the license key, of course.

I'm not sure I like the idea of adding everything to the default components since I think most people aren't going to use anything other than ICC.  Instead, I think what I'll do is add multiple builds, one each for MKL, Fortran, MPI, TBB, etc.  Since you created tests, that will let us verify that each component works as expected without having to manually specify dependencies (e.g., if MKL depends on TBB then `--components mkl` should pull in TBB, too).  I'll play around with it in the next day or two.

**Comment by jeffhammond** [comment]
Yeah, I agree.  I confess that I was sloppy and didn't read the docs thoroughly until after I had changed the default components.  For my purposes, it made sense to enable everything by default, but there is no need for this since one can use the `--components` option.

PS I shared your project on Twitter and G+ this morning, so I guess you will get a few more stars in the near future 😃

**Comment by nemequ** [comment]
I copied all your tests and tried to build with `--components icc,ifort,mpi,daal,ipp,tbb`, and *almost* everything works.  I had to add a component for DAAL, which wasn't a problem.  However, mpiicc and mpiifort don't seem to be installed (see https://travis-ci.org/nemequ/icc-travis/builds/142869336).

I figured maybe I was missing a component you were installing, so I added https://github.com/nemequ/icc-travis/commit/dd93cbf8569c037ca46b7b76515bad6de5bcfe48 to your PR, same result: https://travis-ci.org/nemequ/icc-travis/builds/142916917

Any idea what's going on there?

Other than MPI, everything seems to work; see the staging branch.  I basically just squashed everything into a single commit; sorry, it was too complicated to try to separate out the desirable changes for each commit.

The MPI builds are disabled right now, but if you're okay with what's in staging I'll go ahead and merge that, and try to figure out the issue with MPI when I have some time.  My current theory is that the new release contains new packages for MPI, so I'll download it locally and check the manifest (there is an XML file somewhere which lists all the available packages).

> PS I shared your project on Twitter and G+ this morning, so I guess you will get a few more stars in the near future :smiley:

Thanks :)

**Comment by jeffhammond** [comment]
I wonder if your license does not include Intel MPI.  That might be why it is not installed.  I have seen silent errors of this nature before, which I find extremely frustrating.

**Comment by jeffhammond** [comment]
It works for me, so clearly you have a license key that doesn't include Intel MPI.  Based upon your install-icc.sh, your license is for Composer not Parallel Studio.

I will submit a pull request that will fix this for you 😉

**Comment by nemequ** [comment]
Merged with the new license key for Parallel Studio.  Thanks again for all your work on this; I feel a lot better about this script now that there is some proper testing :)

**Comment by jeffhammond** [comment]
You're the one who did all the hard work.  Writing all those "hello, world" programs was mostly a matter of copy-and-paste 😄 

In any case, I'm already using this infrastructure in the [PRK](https://github.com/ParRes/Kernels) project, which has a massive test matrix, and things are working well (e.g. https://travis-ci.org/jeffhammond/PRK/builds/143470192) and limited only by my stupid mistakes.  Once I get caching setup, the time required to test the Intel builds especially should drop dramatically.

Also, I looked at doing this for Mac, but I'm not sure how easy it is to do a command-line non-interactive install.  I'm embarrassed to admit that I've always used the GUI when installing on my laptop.

**Pull request closed without merging**
