### PR TITLE
Add required components and change license to trial

### PR DESCRIPTION
**Pull request by lawinslow**
Addresses #3 and #4

### CODE REVIEW

**Comment by lawinslow** [comment]
Weird. Worked [here](https://travis-ci.org/lawinslow/icc-travis/builds/100223159#L325). I had changed the install to `sudo` and set the distro to `trusty`. Hmm.

**Comment by lawinslow** [comment]
Ah, ok. @nemequ I got this to work by using `sudo` and [dropping the symlink portion](https://github.com/GLEON/GLM-source/blob/master/install-icc.sh#L174), rather, [calling compilervars.sh](https://github.com/GLEON/GLM-source/blob/master/.travis.yml#L13) in my .travis.yml.  I will make those changes here to get this working (and get a green badge) but that may not be your goal, so you can feel free to close this PR.

**Comment by lawinslow** [comment]
Ah, there we go.

**Comment by lawinslow** [comment]
This may work without sudo and all this other stuff is you don't do the `trial_lic`.

**Comment by nemequ** [comment]
Excellent!  I'll start playing around with it, thank you very much for getting it working!

**Pull request merged**
